// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dct.proto

package dct

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_subrahamanyam341_andes_xyz_data "github.com/subrahamanyam341/andes-xyz/data"
	io "io"
	math "math"
	math_big "math/big"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ESDigitalToken holds the data for a electronic standard digital token transaction
type ESDigitalToken struct {
	Type          uint32        `protobuf:"varint,1,opt,name=Type,proto3" json:"Type"`
	Value         *math_big.Int `protobuf:"bytes,2,opt,name=Value,proto3,casttypewith=math/big.Int;github.com/subrahamanyam341/andes-xyz/data.BigIntCaster" json:"Value"`
	Properties    []byte        `protobuf:"bytes,3,opt,name=Properties,proto3" json:"Properties"`
	TokenMetaData *MetaData     `protobuf:"bytes,4,opt,name=TokenMetaData,proto3" json:"MetaData"`
	Reserved      []byte        `protobuf:"bytes,5,opt,name=Reserved,proto3" json:"Reserved"`
}

func (m *ESDigitalToken) Reset()      { *m = ESDigitalToken{} }
func (*ESDigitalToken) ProtoMessage() {}
func (*ESDigitalToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1cf62b86c79b684, []int{0}
}
func (m *ESDigitalToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ESDigitalToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ESDigitalToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ESDigitalToken.Merge(m, src)
}
func (m *ESDigitalToken) XXX_Size() int {
	return m.Size()
}
func (m *ESDigitalToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ESDigitalToken.DiscardUnknown(m)
}

var xxx_messageInfo_ESDigitalToken proto.InternalMessageInfo

func (m *ESDigitalToken) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ESDigitalToken) GetValue() *math_big.Int {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ESDigitalToken) GetProperties() []byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ESDigitalToken) GetTokenMetaData() *MetaData {
	if m != nil {
		return m.TokenMetaData
	}
	return nil
}

func (m *ESDigitalToken) GetReserved() []byte {
	if m != nil {
		return m.Reserved
	}
	return nil
}

// DCTRoles holds the roles for a given token and the given address
type DCTRoles struct {
	Roles [][]byte `protobuf:"bytes,1,rep,name=Roles,proto3" json:"roles"`
}

func (m *DCTRoles) Reset()      { *m = DCTRoles{} }
func (*DCTRoles) ProtoMessage() {}
func (*DCTRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1cf62b86c79b684, []int{1}
}
func (m *DCTRoles) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DCTRoles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DCTRoles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DCTRoles.Merge(m, src)
}
func (m *DCTRoles) XXX_Size() int {
	return m.Size()
}
func (m *DCTRoles) XXX_DiscardUnknown() {
	xxx_messageInfo_DCTRoles.DiscardUnknown(m)
}

var xxx_messageInfo_DCTRoles proto.InternalMessageInfo

func (m *DCTRoles) GetRoles() [][]byte {
	if m != nil {
		return m.Roles
	}
	return nil
}

// MetaData hold the metadata structure for the DCT token
type MetaData struct {
	Nonce      uint64   `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce"`
	Name       []byte   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	Creator    []byte   `protobuf:"bytes,3,opt,name=Creator,proto3" json:"Creator"`
	Royalties  uint32   `protobuf:"varint,4,opt,name=Royalties,proto3" json:"Royalties"`
	Hash       []byte   `protobuf:"bytes,5,opt,name=Hash,proto3" json:"Hash"`
	URIs       [][]byte `protobuf:"bytes,6,rep,name=URIs,proto3" json:"URIs"`
	Attributes []byte   `protobuf:"bytes,7,opt,name=Attributes,proto3" json:"Attributes"`
}

func (m *MetaData) Reset()      { *m = MetaData{} }
func (*MetaData) ProtoMessage() {}
func (*MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1cf62b86c79b684, []int{2}
}
func (m *MetaData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaData.Merge(m, src)
}
func (m *MetaData) XXX_Size() int {
	return m.Size()
}
func (m *MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_MetaData proto.InternalMessageInfo

func (m *MetaData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MetaData) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MetaData) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MetaData) GetRoyalties() uint32 {
	if m != nil {
		return m.Royalties
	}
	return 0
}

func (m *MetaData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MetaData) GetURIs() [][]byte {
	if m != nil {
		return m.URIs
	}
	return nil
}

func (m *MetaData) GetAttributes() []byte {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*ESDigitalToken)(nil), "protoBuiltInFunctions.ESDigitalToken")
	proto.RegisterType((*DCTRoles)(nil), "protoBuiltInFunctions.DCTRoles")
	proto.RegisterType((*MetaData)(nil), "protoBuiltInFunctions.MetaData")
}

func init() { proto.RegisterFile("dct.proto", fileDescriptor_c1cf62b86c79b684) }

var fileDescriptor_c1cf62b86c79b684 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xbd, 0x8e, 0xd3, 0x4c,
	0x14, 0xf5, 0xe4, 0x67, 0x37, 0x99, 0x4d, 0xb6, 0xb0, 0xf4, 0x49, 0xd6, 0x27, 0x34, 0x8e, 0x22,
	0x21, 0x45, 0x5a, 0xad, 0x23, 0x58, 0x3a, 0x44, 0x81, 0x13, 0x10, 0x29, 0x58, 0xc1, 0x6c, 0xa0,
	0xa0, 0x1b, 0x27, 0x83, 0x63, 0x91, 0x78, 0xa2, 0x99, 0x31, 0x22, 0x54, 0xb4, 0x74, 0x3c, 0x06,
	0xe2, 0x41, 0x10, 0x65, 0xca, 0x54, 0x86, 0x38, 0x0d, 0x72, 0xb5, 0x8f, 0x80, 0xe6, 0x7a, 0xbd,
	0x09, 0x12, 0xcd, 0x9d, 0x73, 0xce, 0x5c, 0xcd, 0xbd, 0x73, 0x0e, 0x6e, 0x4e, 0x27, 0xda, 0x5b,
	0x4a, 0xa1, 0x85, 0xfd, 0x1f, 0x1c, 0x7e, 0x12, 0xcd, 0xf5, 0x28, 0x7e, 0x9a, 0xc4, 0x13, 0x1d,
	0x89, 0x58, 0xfd, 0x7f, 0x1e, 0x46, 0x7a, 0x96, 0x04, 0xde, 0x44, 0x2c, 0xfa, 0xa1, 0x08, 0x45,
	0x1f, 0xda, 0x82, 0xe4, 0x2d, 0x30, 0x20, 0x80, 0x8a, 0x57, 0xba, 0xdf, 0x2b, 0xf8, 0xf4, 0xc9,
	0xd5, 0x30, 0x0a, 0x23, 0xcd, 0xe6, 0x63, 0xf1, 0x8e, 0xc7, 0xf6, 0x1d, 0x5c, 0x1b, 0xaf, 0x96,
	0xdc, 0x41, 0x1d, 0xd4, 0x6b, 0xfb, 0x8d, 0x3c, 0x75, 0x81, 0x53, 0xa8, 0x76, 0x88, 0xeb, 0xaf,
	0xd9, 0x3c, 0xe1, 0x4e, 0xa5, 0x83, 0x7a, 0x2d, 0xff, 0x65, 0x9e, 0xba, 0x85, 0xf0, 0xed, 0xa7,
	0x3b, 0x5c, 0x30, 0x3d, 0xeb, 0x07, 0x51, 0xe8, 0x8d, 0x62, 0xfd, 0xf0, 0x60, 0x11, 0x95, 0x04,
	0x92, 0xcd, 0xd8, 0x82, 0xc5, 0x2b, 0xb6, 0xb8, 0x78, 0x70, 0xaf, 0xcf, 0xe2, 0x29, 0x57, 0xe7,
	0x1f, 0x56, 0x1f, 0xfb, 0x53, 0xa6, 0x99, 0xe7, 0x47, 0xe1, 0x28, 0xd6, 0x03, 0xa6, 0x34, 0x97,
	0xb4, 0x78, 0xce, 0xf6, 0x30, 0x7e, 0x21, 0xc5, 0x92, 0x4b, 0x1d, 0x71, 0xe5, 0x54, 0x61, 0xda,
	0x69, 0x9e, 0xba, 0x07, 0x2a, 0x3d, 0xc0, 0xf6, 0x15, 0x6e, 0xc3, 0xfe, 0xcf, 0xb9, 0x66, 0x43,
	0xa6, 0x99, 0x53, 0xeb, 0xa0, 0xde, 0xc9, 0x7d, 0xd7, 0xfb, 0xa7, 0x4f, 0x5e, 0xd9, 0xe6, 0xb7,
	0xf2, 0xd4, 0x6d, 0x94, 0x8c, 0xfe, 0xfd, 0x86, 0xdd, 0xc3, 0x0d, 0xca, 0x15, 0x97, 0xef, 0xf9,
	0xd4, 0xa9, 0xc3, 0x0a, 0xd0, 0x5e, 0x6a, 0xf4, 0x16, 0x75, 0xcf, 0x70, 0x63, 0x38, 0x18, 0x53,
	0x31, 0xe7, 0xca, 0x76, 0x71, 0x1d, 0x80, 0x83, 0x3a, 0xd5, 0x5e, 0xcb, 0x6f, 0x1a, 0x8f, 0xa4,
	0x11, 0x68, 0xa1, 0x77, 0x3f, 0x57, 0xf0, 0xed, 0x48, 0xd3, 0x7d, 0x29, 0xe2, 0x49, 0x61, 0x78,
	0xad, 0xe8, 0x06, 0x81, 0x16, 0x87, 0x09, 0xe4, 0x92, 0x2d, 0x4a, 0xc7, 0x21, 0x10, 0xc3, 0x29,
	0x54, 0xfb, 0x2e, 0x3e, 0x1e, 0x48, 0xce, 0xb4, 0x90, 0x37, 0x26, 0x9d, 0xe4, 0xa9, 0x5b, 0x4a,
	0xb4, 0x04, 0xf6, 0x19, 0x6e, 0x52, 0xb1, 0x62, 0x73, 0x70, 0xb3, 0x06, 0xd1, 0xb6, 0xf3, 0xd4,
	0xdd, 0x8b, 0x74, 0x0f, 0xcd, 0xc4, 0x67, 0x4c, 0xcd, 0x6e, 0xbe, 0x0c, 0x13, 0x0d, 0xa7, 0x50,
	0xcd, 0xed, 0x2b, 0x3a, 0x52, 0xce, 0x11, 0xfc, 0x0e, 0x6e, 0x0d, 0xa7, 0x50, 0x4d, 0x6e, 0x8f,
	0xb5, 0x96, 0x51, 0x90, 0x68, 0xae, 0x9c, 0xe3, 0x7d, 0x6e, 0x7b, 0x95, 0x1e, 0x60, 0xff, 0xd1,
	0x7a, 0x4b, 0xac, 0xcd, 0x96, 0x58, 0xd7, 0x5b, 0x82, 0x3e, 0x65, 0x04, 0x7d, 0xcd, 0x08, 0xfa,
	0x91, 0x11, 0xb4, 0xce, 0x08, 0xda, 0x64, 0x04, 0xfd, 0xca, 0x08, 0xfa, 0x9d, 0x11, 0xeb, 0x3a,
	0x23, 0xe8, 0xcb, 0x8e, 0x58, 0xeb, 0x1d, 0xb1, 0x36, 0x3b, 0x62, 0xbd, 0xa9, 0x4e, 0x27, 0x3a,
	0x38, 0x82, 0x78, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x15, 0xc1, 0x2f, 0x1a, 0x03,
	0x00, 0x00,
}

func (this *ESDigitalToken) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ESDigitalToken)
	if !ok {
		that2, ok := that.(ESDigitalToken)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	{
		__caster := &github_com_subrahamanyam341_andes_xyz_data.BigIntCaster{}
		if !__caster.Equal(this.Value, that1.Value) {
			return false
		}
	}
	if !bytes.Equal(this.Properties, that1.Properties) {
		return false
	}
	if !this.TokenMetaData.Equal(that1.TokenMetaData) {
		return false
	}
	if !bytes.Equal(this.Reserved, that1.Reserved) {
		return false
	}
	return true
}
func (this *DCTRoles) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DCTRoles)
	if !ok {
		that2, ok := that.(DCTRoles)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Roles) != len(that1.Roles) {
		return false
	}
	for i := range this.Roles {
		if !bytes.Equal(this.Roles[i], that1.Roles[i]) {
			return false
		}
	}
	return true
}
func (this *MetaData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MetaData)
	if !ok {
		that2, ok := that.(MetaData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.Name, that1.Name) {
		return false
	}
	if !bytes.Equal(this.Creator, that1.Creator) {
		return false
	}
	if this.Royalties != that1.Royalties {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	if len(this.URIs) != len(that1.URIs) {
		return false
	}
	for i := range this.URIs {
		if !bytes.Equal(this.URIs[i], that1.URIs[i]) {
			return false
		}
	}
	if !bytes.Equal(this.Attributes, that1.Attributes) {
		return false
	}
	return true
}
func (this *ESDigitalToken) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&dct.ESDigitalToken{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "Properties: "+fmt.Sprintf("%#v", this.Properties)+",\n")
	if this.TokenMetaData != nil {
		s = append(s, "TokenMetaData: "+fmt.Sprintf("%#v", this.TokenMetaData)+",\n")
	}
	s = append(s, "Reserved: "+fmt.Sprintf("%#v", this.Reserved)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DCTRoles) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&dct.DCTRoles{")
	s = append(s, "Roles: "+fmt.Sprintf("%#v", this.Roles)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MetaData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&dct.MetaData{")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Creator: "+fmt.Sprintf("%#v", this.Creator)+",\n")
	s = append(s, "Royalties: "+fmt.Sprintf("%#v", this.Royalties)+",\n")
	s = append(s, "Hash: "+fmt.Sprintf("%#v", this.Hash)+",\n")
	s = append(s, "URIs: "+fmt.Sprintf("%#v", this.URIs)+",\n")
	s = append(s, "Attributes: "+fmt.Sprintf("%#v", this.Attributes)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringDct(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ESDigitalToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ESDigitalToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ESDigitalToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reserved) > 0 {
		i -= len(m.Reserved)
		copy(dAtA[i:], m.Reserved)
		i = encodeVarintDct(dAtA, i, uint64(len(m.Reserved)))
		i--
		dAtA[i] = 0x2a
	}
	if m.TokenMetaData != nil {
		{
			size, err := m.TokenMetaData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDct(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Properties) > 0 {
		i -= len(m.Properties)
		copy(dAtA[i:], m.Properties)
		i = encodeVarintDct(dAtA, i, uint64(len(m.Properties)))
		i--
		dAtA[i] = 0x1a
	}
	{
		__caster := &github_com_subrahamanyam341_andes_xyz_data.BigIntCaster{}
		size := __caster.Size(m.Value)
		i -= size
		if _, err := __caster.MarshalTo(m.Value, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDct(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Type != 0 {
		i = encodeVarintDct(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DCTRoles) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DCTRoles) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DCTRoles) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Roles) > 0 {
		for iNdEx := len(m.Roles) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Roles[iNdEx])
			copy(dAtA[i:], m.Roles[iNdEx])
			i = encodeVarintDct(dAtA, i, uint64(len(m.Roles[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MetaData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetaData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attributes) > 0 {
		i -= len(m.Attributes)
		copy(dAtA[i:], m.Attributes)
		i = encodeVarintDct(dAtA, i, uint64(len(m.Attributes)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.URIs) > 0 {
		for iNdEx := len(m.URIs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.URIs[iNdEx])
			copy(dAtA[i:], m.URIs[iNdEx])
			i = encodeVarintDct(dAtA, i, uint64(len(m.URIs[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintDct(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Royalties != 0 {
		i = encodeVarintDct(dAtA, i, uint64(m.Royalties))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDct(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintDct(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintDct(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDct(dAtA []byte, offset int, v uint64) int {
	offset -= sovDct(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ESDigitalToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovDct(uint64(m.Type))
	}
	{
		__caster := &github_com_subrahamanyam341_andes_xyz_data.BigIntCaster{}
		l = __caster.Size(m.Value)
		n += 1 + l + sovDct(uint64(l))
	}
	l = len(m.Properties)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	if m.TokenMetaData != nil {
		l = m.TokenMetaData.Size()
		n += 1 + l + sovDct(uint64(l))
	}
	l = len(m.Reserved)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	return n
}

func (m *DCTRoles) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Roles) > 0 {
		for _, b := range m.Roles {
			l = len(b)
			n += 1 + l + sovDct(uint64(l))
		}
	}
	return n
}

func (m *MetaData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovDct(uint64(m.Nonce))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	if m.Royalties != 0 {
		n += 1 + sovDct(uint64(m.Royalties))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	if len(m.URIs) > 0 {
		for _, b := range m.URIs {
			l = len(b)
			n += 1 + l + sovDct(uint64(l))
		}
	}
	l = len(m.Attributes)
	if l > 0 {
		n += 1 + l + sovDct(uint64(l))
	}
	return n
}

func sovDct(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDct(x uint64) (n int) {
	return sovDct(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ESDigitalToken) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ESDigitalToken{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`Properties:` + fmt.Sprintf("%v", this.Properties) + `,`,
		`TokenMetaData:` + strings.Replace(this.TokenMetaData.String(), "MetaData", "MetaData", 1) + `,`,
		`Reserved:` + fmt.Sprintf("%v", this.Reserved) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DCTRoles) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DCTRoles{`,
		`Roles:` + fmt.Sprintf("%v", this.Roles) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MetaData) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MetaData{`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Creator:` + fmt.Sprintf("%v", this.Creator) + `,`,
		`Royalties:` + fmt.Sprintf("%v", this.Royalties) + `,`,
		`Hash:` + fmt.Sprintf("%v", this.Hash) + `,`,
		`URIs:` + fmt.Sprintf("%v", this.URIs) + `,`,
		`Attributes:` + fmt.Sprintf("%v", this.Attributes) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringDct(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ESDigitalToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ESDigitalToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ESDigitalToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_subrahamanyam341_andes_xyz_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.Value = tmp
				}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Properties", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Properties = append(m.Properties[:0], dAtA[iNdEx:postIndex]...)
			if m.Properties == nil {
				m.Properties = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenMetaData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TokenMetaData == nil {
				m.TokenMetaData = &MetaData{}
			}
			if err := m.TokenMetaData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserved", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserved = append(m.Reserved[:0], dAtA[iNdEx:postIndex]...)
			if m.Reserved == nil {
				m.Reserved = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DCTRoles) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DCTRoles: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DCTRoles: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roles = append(m.Roles, make([]byte, postIndex-iNdEx))
			copy(m.Roles[len(m.Roles)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetaData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDct
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = append(m.Name[:0], dAtA[iNdEx:postIndex]...)
			if m.Name == nil {
				m.Name = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Royalties", wireType)
			}
			m.Royalties = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Royalties |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URIs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URIs = append(m.URIs, make([]byte, postIndex-iNdEx))
			copy(m.URIs[len(m.URIs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDct
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDct
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDct
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes[:0], dAtA[iNdEx:postIndex]...)
			if m.Attributes == nil {
				m.Attributes = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDct(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDct
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDct(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDct
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDct
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDct
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDct
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDct
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDct
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDct        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDct          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDct = fmt.Errorf("proto: unexpected end of group")
)
